---
- hosts: localhost
  remote_user: root
  tasks:
    - name: Bajando Pagina
      shell: /etc/ansible/BonusProd/pag_mantenimiento_down.sh 
    - name: Notificacion Telegram 
      shell: /etc/ansible/BonusProd/smsDOWN.sh
    - name: Notificacion SMS
      shell: /etc/ansible/BonusProd/notificacionLoteDown.sh

- hosts: ProdJbossWeb
  remote_user: root
  tasks:
    - name: Bajando Jboss Web
      service:
       name: jboss-as-standalone
       state: stopped
- hosts: ProdJbossTrans
  remote_user: root
  tasks:
    - name: Bajando Jboss Trans
      service:
       name: jboss-as-standalone
       state: stopped
- hosts: ProdJbossGX
  remote_user: root
  tasks:
    - name: Bajando Jboss GX
      command: killall -9 java
- hosts: ProdJbossBC
  remote_user: root
  tasks:
    - name: Bajando Jboss BC
      service:
       name: jboss-as-standalone
       state: stopped
- hosts: ProdJbossArchivos
  remote_user: root
  tasks:
    - name: Bajando Jboss Archivos
      service:
       name: jboss-as-standalone
       state: stopped
- hosts: ProdJbossESBTRA
  remote_user: root
  tasks:
    - name: Bajando Jboss ESBTRA
      service:
       name: jboss-eap-rhel
       state: stopped 
---
- hosts: JBossIgdoc
  remote_user: root
  tasks:
    - name: Stop service jboss
      service:
       name: jboss-eap-slave
       state: stopped
---
- hosts: JBossCaja
  remote_user: root
  tasks:
    - name: Stop service jboss
      service:
       name: jboss-eap-slave
       state: stopped
---
- hosts: JBossCNB
  remote_user: root
  tasks:
    - name: Stop service jboss
      service:
       name: jboss-eap-slave
       state: stopped
---
- hosts: JBossHbanking
  remote_user: root
  tasks:
    - name: Stop service jboss
      service:
       name: jboss-eap-slave
       state: stopped
---
- hosts: JBossJbvarios
  remote_user: root
  tasks:
    - name: Stop service jboss
      service:
       name: jboss-eap-slave
       state: stopped
---
- hosts: JBossBusbancard
  remote_user: root
  tasks:
    - name: Stop service jboss
      service:
sts: JbossStandaloneADMRest
  remote_user: root
  tasks:
    - name: Stop service jboss
      service:
       name: jboss-as-standalone
       state: stopped
---
- hosts: JbossStandaloneFormalistica
  remote_user: root
  tasks:
    - name: Stop jboss service
      service:
       name: jboss-as-standalone
       state: stopped
---
- hosts: JbossStandaloneInformconf
  remote_user: root
  tasks:
    - name: Stop jboss service
      service:
       name: jboss-as-standalone
       state: stopped
---
- hosts: JbossStandaloneProforma
  remote_user: root
  tasks:
    - name: Stop jboss service
      service:
       name: jboss-as-standalone
       state: stopped
       name: jboss-eap-slave
       state: stopped
---
- hosts: JbossStandalonePanel
  remote_user: root
  tasks:
    - name: Stop service jboss
      service:
       name: jboss-as-standalone
---
- hosts: JbossStandaloneBilletera
  remote_user: root
  tasks:
    - name: Stop jboss service
      service:
       name: jboss-as-standalone
       state: stopped
---
- hosts: JbossStandaloneTauser 
  remote_user: root
  tasks:
    - name: Stop service jboss
      service:
       name: jboss-as-standalone
       state: stopped
---
- hosts: JbossStandaloneTruncamiento
  remote_user: root
  tasks:
    - name: Stop jboss service
      service:
       name: jboss-as-standalone
       state: stopped
---
- hosts: JbossStandaloneDepox
  remote_user: root
  tasks:
    - name: Stop jboss service
      service:
       name: jboss-as-standalone
       state: stopped
---
- hosts: JbossStandaloneTelco
  remote_user: root
  tasks:
    - name: Stop jboss service
      service:
       name: jboss-as-standalone
       state: stopped
---
- hosts: JbossStandalone724
  remote_user: root
  tasks:
    - name: Stop jboss service
      service:
       name: jboss-as-standalone
       state: stopped
---
- hosts: JBossStandalone
  remote_user: root
  tasks:
    - name: Stop service Jboss
      service:
       name: jboss-as-standalone
       state: stopped
---
- hosts: JbossStandaloneToken
  remote_user: root
  tasks:
    - name: Stop jboss service
      service:
       name: jboss-as-standalone
       state: stopped
---
- hosts: JbossStandaloneSms
  remote_user: root
  tasks:
    - name: Stop service Jboss
      service:
       name: jboss-as-standalone
       state: stopped
---
- hosts: JbossHQSMS
  remote_user: root
  tasks:
    - name: Stop service Jboss
      service:
       name: jboss-as-standalone
       state: stopped
---
- hosts: JbossStandaloneLogin
  remote_user: root
  tasks:
    - name: Stop service jboss
      service:
       name: jboss-as-standalone
       state: stopped
---
- hosts: BancardIgdoc
  remote_user: root
  tasks:
    - name: Stop service jboss
      service:
       name: wildfly-init-redhat
       state: stopped
---
- hosts: BancardBonus
  remote_user: root
  tasks:
    - name: Stop service jboss
      service:
       name: wildfly-init-redhat
       state: stopped
       
