---
- hosts: JbossStandaloneSms
  remote_user: root
  tasks:
    - name: Stop service Jboss
      service:
       name: jboss-as-standalone
       state: stopped
---
- hosts: JbossHQSMS
  remote_user: root
  tasks:
    - name: Stop service Jboss
      service:
       name: jboss-as-standalone
       state: stopped

