---
- hosts: ProdJbossGX
  remote_user: root	
  tasks:
  - name: Habilitar el contexto de los JbossWeb Prod en el Apache 10.20.1.106
    command: curl http://10.20.1.106:6666/mc?Cmd=ENABLE-APP&Range=NODE&JVMRoute={{ ansible_hostname }}

- hosts: ProdJbossGX
  remote_user: root
  tasks:
  - name: Habilitar el contexto de los JbossWeb Prod en el Apache 10.20.1.111
    command: curl http://10.20.1.111:6666/mc?Cmd=ENABLE-APP&Range=NODE&JVMRoute={{ ansible_hostname }}

- hosts: ProdJbossWeb
  remote_user: root
  tasks:
  - name: Habilitar el contexto de los JbossWeb Prod en el Apache 10.20.1.136
    command: curl http://10.20.1.136:6666/mc?Cmd=ENABLE-APP&Range=NODE&JVMRoute={{ ansible_hostname }}

- hosts: ProdJbossWeb
  remote_user: root
  tasks:
  - name: Habilitar el contexto de los JbossWeb Prod en el Apache 10.20.1.143
    command: curl http://10.20.1.143:6666/mc?Cmd=ENABLE-APP&Range=NODE&JVMRoute={{ ansible_hostname }}

- hosts: ProdJbossTrans
  remote_user: root
  tasks:
  - name: Habilitar el contexto de los JbossWeb Prod en el Apache 10.22.1.22
    command: curl http://10.22.1.22:6666/mc?Cmd=ENABLE-APP&Range=NODE&JVMRoute={{ ansible_hostname }}

- hosts: ProdJbossTrans
  remote_user: root
  tasks:
  - name: Habilitar el contexto de los JbossWeb Prod en el Apache 10.22.1.21
    command: curl http://10.22.1.21:6666/mc?Cmd=ENABLE-APP&Range=NODE&JVMRoute={{ ansible_hostname }}

